### ISSUE TITLE
Pipeline fails when cache = true

### ISSUE THREAD

**Issue by bschonec** [jw3/mock-rpm#12]
I assume that the workflow action is attempting to build the image for the first time.  It fails somewhere around [here](https://github.com/jw3/mock-rpm/blob/f4d74ca59008c4eb00088fbb787c71a98de898e0/action.yml#L87).  The "f" is missing from "fedora:latest".

This is my simple workflow:

```
      - uses: jw3/mock-rpm@v1
        id: rpmbuild
        with:
          chroot: ${{ matrix.mocks }}
          spec: test/simple/hello.spec
          cache: true

```

```
Run cid=$(cat action.cid)
  cid=$(cat action.cid)
  iid="-fedora:latest"
  podman commit $cid $iid
  mkdir -p /tmp/mock
  podman save $iid | gzip > /tmp/cache/image.tar.gz
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  
Error: unrecognized image format "edora:latest"
Error: Process completed with exit code 125.
```
